### PR TITLE
Modified wording to explicitly mention assigning roles

### PR DESCRIPTION
**Pull request by Ronak06**
Modified section pertaining to roles required to explicitly outline that users will need to assign the roles at the project level to their respective user/service account. The current documentation outlines to "Assign the following permissions" which can cause confusion.

## Pull Request Template
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. **Before** submitting the PR, review your changes:
    * Adjust the code to the existing [style](https://google.github.io/styleguide).
    * Add a set of unit tests for the changes and ensure they all pass.
    * Add accompanying README.md file with instructions on usage. See [awesome-readme](https://github.com/matiassingers/awesome-readme) for good examples of high-quality READMEs.
    * Add a link to your contribution in the top-level [README](https://github.com/GoogleCloudPlatform/professional-services/blob/master/README.md) (alpha-order).
    * Add [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license headers with an up-to-date copyright date attributed to `Google LLC`.
    * Remove unnecessary LICENSE files. There's no need to include an additional license since all repository submissions are covered by the top-level Apache 2.0 [license](https://github.com/GoogleCloudPlatform/professional-services/blob/master/LICENSE).
    * **For new tools/examples**, file your project with the PSO Engineering Council.

3. **After** these steps, you're ready to open a pull request.
    * Give a descriptive title to your PR.
    * Provide a description of your changes.
    * Include the Engineering Council bug ID with your pull request.
    * Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
<br/>

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by boredabdel** [comment]
Hi @Ronak06 

Thanks for the PR. We will need you to Sign the Google CLA (https://cla.developers.google.com/) before we can accept this PR. Otherwise GH will not allow us to merge it

Thanks

**Comment by Ronak06** [comment]
Hi @boredabdel, thank you for the link to sign the Google CLA. I have just signed it now. Please let me know if there's anything else I can be of assistance with to help accept this PR.

**Review by boredabdel — APPROVED** [review]
LGTM

**Comment by boredabdel** [comment]
Hi @Ronak06 Thanks but i still have an issue. Can you please make sure you have signed the CLA using the same email you used to commit this PR ?

**Comment by boredabdel** [comment]
@Ronak06 did you had a chance to look at this ?

**Comment by Ronak06** [comment]
Apologies for the late reply Abdel! It appears I was logged into another account which had the CLA signed. I have signed the CLA now for this current account. Please let me know if there is anything else needed from my end. Thank you for your help!

**Comment by boredabdel** [comment]
Thank you !

**Pull request merged**
