### PR TITLE
Fix bugs in main.py as it fails on VMs with multiple disks and custom device names

### PR DESCRIPTION
**Pull request by shashyajoshi**
Here are the current bugs with this script with respective fixes

1. key_name variable assignment is inside the for loop. It fails on the second iteration, as the key_name keeps getting added to its previous value. This is fixed by moving that line outside of the for loop, next to zone and region assignments
2. The API call for detach disk needs DeviceName field and not disk_name. Added the variable device_name to get the DeviceName and used it in the detach_disk function call
3. Line #294 has an error with "end" which is not expected there with only one %s for "operation".

## Pull Request Template
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. **Before** submitting the PR, review your changes:
    * Adjust the code to the existing [style](https://google.github.io/styleguide).
    * Add a set of unit tests for the changes and ensure they all pass.
    * Add accompanying README.md file with instructions on usage. See [awesome-readme](https://github.com/matiassingers/awesome-readme) for good examples of high-quality READMEs.
    * Add a link to your contribution in the top-level [README](https://github.com/GoogleCloudPlatform/professional-services/blob/master/README.md) (alpha-order).
    * Add [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license headers with an up-to-date copyright date attributed to `Google LLC`.
    * Remove unnecessary LICENSE files. There's no need to include an additional license since all repository submissions are covered by the top-level Apache 2.0 [license](https://github.com/GoogleCloudPlatform/professional-services/blob/master/LICENSE).
    * **For new tools/examples**, file your project with the PSO Engineering Council.

3. **After** these steps, you're ready to open a pull request.
    * Give a descriptive title to your PR.
    * Provide a description of your changes.
    * Include the Engineering Council bug ID with your pull request.
    * Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
<br/>

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Review by boredabdel — APPROVED** [review]
LGTM

**Comment by boredabdel** [comment]
shashyajoshi@ the PR has some conflicts, can you please rebase and commit so i can merge it

**Comment by shashyajoshi** [comment]
@boredabdel rebased and realized that one of the three items I wanted to fix was fixed already but then I found one new bug in my testing. I have created a new pull request now that covers two items from my last PR and one new.

**Comment by boredabdel** [comment]
Ok great will close this one than

**Pull request closed without merging**
