### PR TITLE
Added top 10 usage consumption table

### PR DESCRIPTION
**Pull request by kimjulia1117**
-Updated the README file to show the new Data Studio dashboard to show the top 10 usage consumption table
-Removed aggregation related code in the ScanProjectQuotasHelper.java + ScanProjectQuotas.java to get the most updated quota limit

### CODE REVIEW

**Review by boredabdel — APPROVED** [review]
LGTM

**Comment by saurabh-deochake** [comment]
We are also receiving the same error as mentioned by @mkadriDevops above.

**Pull request merged**
