### PR TITLE
Python Dataflow code example optimize

### PR DESCRIPTION
**Pull request by shubhamdangare**
- Python Dataflow code example optimize

### CODE REVIEW

**Review by boredabdel — APPROVED** [review]
LGTM

**Comment by liveabilityment360** [comment]
I was trying to insert multiple csv files from cloud storage to big query using the below link, but getting an error " attributeerror: 'filecoder' object has no attribute 'to_type_hint'" . Can someone please help me on this

https://github.com/GoogleCloudPlatform/professional-services/blob/main/examples/dataflow-python-examples/batch-examples/cookbook-examples/pipelines/data_ingestion_configurable.py

**Pull request merged**
