### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by larchiu**
update typo on terraform

### CODE REVIEW

**Comment by iht** [comment]
Thanks for tidying that doc up!

**Comment by iht** [comment]
Now I have just realized this should be sent to main, not master...

**Comment by larchiu** [comment]
Hi Israel, do you need my help?

**Comment by larchiu** [comment]
iht, created another PR - https://github.com/GoogleCloudPlatform/professional-services/pull/585

**Pull request merged**
