### PR TITLE
[SLO-Generator] WIP - Add timeZone argument

### PR DESCRIPTION
**Pull request by bkamin29**
Add timezone argument

## Pull Request Template
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. **Before** submitting the PR, review your changes:
    * Adjust the code to the existing [style](https://google.github.io/styleguide).
    * Add a set of unit tests for the changes and ensure they all pass.
    * Add accompanying README.md file with instructions on usage. See [awesome-readme](https://github.com/matiassingers/awesome-readme) for good examples of high-quality READMEs.
    * Add a link to your contribution in the top-level [README](https://github.com/GoogleCloudPlatform/professional-services/blob/master/README.md) (alpha-order).
    * Add [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license headers with an up-to-date copyright date attributed to `Google LLC`.
    * Remove unnecessary LICENSE files. There's no need to include an additional license since all repository submissions are covered by the top-level Apache 2.0 [license](https://github.com/GoogleCloudPlatform/professional-services/blob/master/LICENSE).
    * **For new tools/examples**, file your project with the PSO Engineering Council.

3. **After** these steps, you're ready to open a pull request.
    * Give a descriptive title to your PR.
    * Provide a description of your changes.
    * Include the Engineering Council bug ID with your pull request.
    * Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
<br/>

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by ocervell** [comment]
@benesis002 we should make the timezone argument optional: if not passed, take the default locale where the environment is running (e.g: if running a Cloud Function in eu-west, take this timezone. What do you think ?

**Comment by benesis002** [comment]
> @benesis002 we should make the timezone argument optional: if not passed, take the default locale where the environment is running (e.g: if running a Cloud Function in eu-west, take this timezone. What do you think ?

Yes et no. Maybe by default we have to use the GMT timezone (on Python part)
In the terraform module we can override this value with the Cloud Function timezone

**Comment by ocervell** [comment]
@bkamin29 if you haven't started yet, I encourage you to open your PR in the new repo: https://github.com/google/slo-generator

**Comment by bkamin29** [comment]
> @bkamin29 if you haven't started yet, I encourage you to open your PR in the new repo: https://github.com/google/slo-generator (and close this PR)

Not startes so i have created https://github.com/google/slo-generator/issues/40

**Pull request closed without merging**
