### PR TITLE
Bmenasha/cai fix issue 900

### LINKED ISSUE #900: asset inventory dataflow jobs failing with "The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING." and "A hot key was detected in step"
8 days ago we started getting the following dataflow errors in the asset-inventory tool:

"google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING. [while running 'load_to_bigquery-ptransform-27'] === Source Location Trace: === dist_proc/dax/workflow/worker/fnapi_sdk_harness.cc:178"

"A hot key was detected in step 'group_by_key_before_enforce/Read+enforce_schema+group_by_key_before_write/Write' with age of 1m57.513412938s. This is a symptom of key distribution being skewed. To fix, please inspect your data and pipeline to ensure that elements are evenly distributed across your key space."
 
The asset-inventory is set to overwrite the BigQuery tables on each run and no changes were made to the resources prior to seeing the error.  

Any assistance or suggestions at fixing this issue would be much appreciated.

Cheers,
Dante

**Error Logs:**

`{
  "insertId": "2598849684236876365:261148:0:172781",
  "jsonPayload": {
    "thread": "244",
    "line": "hot_key_logger.cc:169",
    "message": "A hot key was detected in step 'group_by_key_before_enforce/Read+enforce_schema+group_by_key_before_write/Write' with age of 1m57.513412938s. This is a symptom of key distribution being skewed. To fix, please inspect your data and pipeline to ensure that elements are evenly distributed across your key space."
  },
  "resource": {
    "type": "dataflow_step",
    "labels": {
      "project_id": "****",
      "step_id": "",
      "job_name": "cloud-asset-import-2022-10-06t07-32-18-998964",
      "job_id": "2022-10-06_00_32_19-16094098302119097546",
      "region": "us-central1"
    }
  },
  "timestamp": "2022-10-06T07:54:30.004049Z",
  "severity": "WARNING",
  "labels": {
    "dataflow.googleapis.com/job_name": "cloud-asset-import-2022-10-06t07-32-18-998964",
    "dataflow.googleapis.com/log_type": "system",
    "compute.googleapis.com/resource_id": "2598849684236876365",
    "dataflow.googleapis.com/region": "us-central1",
    "compute.googleapis.com/resource_name": "cloud-asset-import-2022-1-10060032-hd41-harness-p6z1",
    "dataflow.googleapis.com/job_id": "2022-10-06_00_32_19-16094098302119097546",
    "compute.googleapis.com/resource_type": "instance"
  },
  "logName": "projects/*****/logs/dataflow.googleapis.com%2Fharness",
  "receiveTimestamp": "2022-10-06T07:54:58.087488001Z"
}`

Workflow failed. Causes: S19:group_written_objects_by_key/Read+delete_tables+load_to_bigquery failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these workers: 

  cloud-asset-import-2022-1-10060032-hd41-harness-p6z1
      Root cause: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute
    response = task()
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 597, in do_instruction
    return getattr(self, request_type)(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 227, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1491, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 623, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1581, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1694, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1507, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING. [while running 'load_to_bigquery-ptransform-27']
,

  cloud-asset-import-2022-1-10060032-hd41-harness-p6z1
      Root cause: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute
    response = task()
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 597, in do_instruction
    return getattr(self, request_type)(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 227, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1491, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 623, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1581, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1694, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1507, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING. [while running 'load_to_bigquery-ptransform-27']
,

  cloud-asset-import-2022-1-10060032-hd41-harness-p6z1
      Root cause: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute
    response = task()
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 597, in do_instruction
    return getattr(self, request_type)(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 227, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1491, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 623, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1581, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1694, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1507, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING. [while running 'load_to_bigquery-ptransform-27']
,

  cloud-asset-import-2022-1-10060032-hd41-harness-p6z1
      Root cause: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 284, in _execute
    response = task()
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 357, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 597, in do_instruction
    return getattr(self, request_type)(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/sdk_worker.py", line 635, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1003, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/usr/local/lib/python3.9/site-packages/apache_beam/runners/worker/bundle_processor.py", line 227, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 528, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 237, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1491, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 623, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1581, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1694, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 240, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 907, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 908, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1419, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1507, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1417, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 837, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 983, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 423, in process
  File "/home/bmenasha/workspace/professional-services/tools/asset-inventory/./asset_inventory/import_pipeline.py", line 412, in process
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 2350, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 510, in _begin
    api_response = client._call_api(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/security-asset-inventory/jobs?prettyPrint=false: The field specified for time partitioning can only be of type TIMESTAMP, DATE or DATETIME. The type found is: STRING. [while running 'load_to_bigquery-ptransform-27']

### PR DESCRIPTION
**Pull request by bmenasha**
Don't overide the `timestamp` field's type.

- Closes #900 by not overriding timestamp's type from `timestamp` to string as it's
  used as a table partition.

- Performance improvements:

  - Don't perform a deep copy of the destination field within _merge_fields,
    it's not necessary as it's always a new object and Cloud Profiler says it
    was resource intensive.

  - Don't deep copy the 'data' field within ProduceResourceJson by removing it
    prior to the deep copy and adding it back to the element after.

- Fix a bug where enforce_schema wouldn't work because it yieled the original
  elements, it needs to yeild a new element key pair.

- Fix a bug when sharding asset types were we would delete the table while
  loading because not all shards were processed before deleting and loading
  occured. To fix this we now group by table name after WriteToGCS rather then
  shard key. Then assign back the sharded prior to loading.

### CODE REVIEW

**Comment by bmenasha** [comment]
can someone review this? thanks

**Comment by bmenasha** [comment]
can someone review this?
 thanks

**Comment by bmenasha** [comment]
There is another fix I wish to commit for issue #910  but they depend on this being merged. 
Can someone please review this? 
thanks
Ben

**Review by ojmendezz — APPROVED** [review]
LGTM

**Review by agold-rh — APPROVED** [review]

**Pull request merged**
