### PR TITLE
Copy data from bucket that is not public anymore (and add Git LFS)

### PR DESCRIPTION
**Pull request by iht**
This copies some data from a bucket that is not available anymore, fixes some links (all except notebooks) to that data, and adds Git LFS configuration for the data files (they are not huge, the largest is 28 MB compressed, but it still makes operating with the repo slower unless LFS is used).

Partially addresses #601

### CODE REVIEW

**Review by boredabdel — APPROVED** [review]
LGTM

**Comment by JoseGuilhermeDoZe** [comment]
@boredabdel @iht   Please where is the file https://storage.googleapis.com/gcp_blog/e2e_demo/model.tar  ??

**Pull request merged**
