### PR TITLE
Minor fix for code Optimize

### PR DESCRIPTION
**Pull request by shubhamdangare**
Description :- Code Optimize for example file for python-data-flow

### CODE REVIEW

**Comment by shubhamdangare** [comment]
@googlebot I fixed it

**Comment by boredabdel** [comment]
Hi Shubham

Happy to accept this but we will need you to sign the Contributor License Agreements. You can find more details [here](https://cla.developers.google.com/)

**Comment by shubhamdangare** [comment]
@boredabdel have added that check in [](https://github.com/GoogleCloudPlatform/professional-services/pull/661)

**Comment by shubhamdangare** [comment]
@googlebot I fixed it

**Pull request closed without merging**
