### PR TITLE
Tool to detect recency of terraform remote module tags

### PR DESCRIPTION
**Pull request by jmound**
- Git tag recency sorting is handled by `sort`'s `-V`:
https://github.com/GoogleCloudPlatform/professional-services/blob/56425260ba2482e5eb50160636bf9d58c0decd76/tools/terraform-module-update-scanner/check-terraform-module-versions#L46
which is not entirely reliable- it of course depends on the remote authors' versioning scheme. Suggestions are welcome as to how to improve the method of determining the latest tag.

### CODE REVIEW

**Comment by morgante** [comment]
Bump.

**Comment by jmound** [comment]
@morgante updated.

**Comment by morgante** [comment]
@jmound Please ping me once you've fixed the test cases.

**Comment by jmound** [comment]
@morgante I've updated the code to handle prefix-styled tags, and added small updates to the tests as well.

**Pull request merged**
