### PR TITLE
Add a Storm to Beam conversion utility

### PR DESCRIPTION
**Pull request by svetakvsundhar**
This PR adds a colab notebook as a template for a user to upload a code file, describe their Beam pipeline, and make a Gemini API call to have Apache Storm pseudocode/design diagrams generated. Note that this utility does not guarantee correctness, and is primarily in place to speed-run the process to make the API call.

The link to review this notebook is here: https://colab.sandbox.google.com/drive/1iTrWBqA9pSpKIdt9Ua-rnDZM113-WXtQ#scrollTo=8YkEn_rKg8eb

### CODE REVIEW

**Comment by svetakvsundhar** [comment]
R: @iht 
R: @ryanmcdowell

**Comment by iht** [comment]
@svetakvsundhar I am getting access denied to the linked Colab notebook for review

**Comment by svetakvsundhar** [comment]
@iht shared

**Review by iht — APPROVED** [review]

**Pull request merged**
