### PR TITLE
Hive BigQuery Generator

### PR DESCRIPTION
**Pull request by nikunjbhartia**
This is a tool which reads from Hive Metastore via thrift and creates bigquery external tables on the GCS buckets pointed by different hive tables. This also created BigQuery views on top of the external tables and does some required transformations for handling hive timestamp and bigquery datetime.

### CODE REVIEW

**Comment by mandeeptrehan** [comment]
@nikunjbhartia Can we clean up .grade directory?

**Review by mandeeptrehan — APPROVED** [review]

**Review by mandeeptrehan — APPROVED** [review]
LGTM

**Comment by agold-rh** [comment]
@nikunjbhartia The build trigger is failing. If you can fix the build error, I can work on getting this PR merged.

**Comment by agold-rh** [comment]
The build trigger generates the following error:

Some files need to be formatted in ./tools/hive-bigquery-generator - FAIL
./tools/hive-bigquery-generator/docker/run.sh ./tools/hive-bigquery-generator/localrun/local_build.sh ./tools/hive-bigquery-generator/localrun/run.sh ./tools/hive-bigquery-generator/run.sh ./tools/hive-bigquery-generator/cloudrun/create_artifact_registry.sh ./tools/hive-bigquery-generator/cloudrun/run.sh 
make: *** [Makefile:28: test] Error 1

Look in the top level "helpers" folder to review the project formatting tests, etc.

**Comment by agold-rh** [comment]
@nikunjbhartia If you can fix the conflicts, I can probably get this merged.

**Comment by nikunjbhartia** [comment]
Hey @agold-rh thanks for looking into this. 
Let me work on cleaning this up and get back to you.

**Comment by agold-rh** [comment]
Closing due to inactivity.

**Pull request closed without merging**
