### PR TITLE
gRPC Spanner Example 

### PR DESCRIPTION
**Pull request by carolinahdez**
This example creates a gRCP server that connect to spanner to find the name of user for a given user id.

### CODE REVIEW

**Comment by boredabdel** [comment]
Hi,

The CI is failing for this PR. Can you please follow the contributor guide https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md to run the linter and formatter locally and amend your changes to this commit

Cheers

**Comment by carolinahdez** [comment]
> https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md

I have already run your suggestions and the code is reformatted using intellij google style. The messages are not very helpful to figure out what I need to clean.   Can you help out?

Some files need to be formatted in ./examples/grpc_spanner_example - FAIL
./examples/grpc_spanner_example/src/main/java/com/example/grpc/server/ConnectServer.java
./examples/grpc_spanner_example/src/main/java/com/example/grpc/service/ConnectServiceImpl.java
./examples/grpc_spanner_example/src/main/java/com/example/grpc/service/SpannerUtil.java
./examples/grpc_spanner_example/src/main/java/com/example/grpc/client/ConnectClient.java

**Comment by carolinahdez** [comment]
> The CI is failing for this PR. Can you please follow the contributor guide https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md to run the linter and formatter locally and amend your changes to this commit

Following the output of run the linter locally. As you can see it pass for the directory that I am trying to merge:
I have not idea what to fix.

Validating ./examples/grpc_spanner_example - Checking bash files
No bash files found for ./examples/grpc_spanner_example - SKIP
Validating ./examples/grpc_spanner_example - Checking GO files
No go files need formatting for ./examples/grpc_spanner_example - SKIP
Validating ./examples/grpc_spanner_example - Checking java files
Testing formatting for java files in ./examples/grpc_spanner_example
No files need to be formatted in ./examples/grpc_spanner_example - PASS
Validating ./examples/grpc_spanner_example - Checking python files
No python files found for ./examples/grpc_spanner_example - SKIP

**Comment by boredabdel** [comment]
I run the formted and linter on this PR and the linter passed. You have to format the code first and than try the linter. After that you will be able to commit the changes (with --amend so they are added to the same PR)

Run the formtter

```docker run \
  --mount type=bind,source="$( pwd )",target=/workspace \
  --workdir=/workspace \
  gcr.io/$(gcloud config get-value project)/make fmt```

Run the linter

```docker run \
  --mount type=bind,source="$( pwd )",target=/workspace \
  --workdir=/workspace \
  gcr.io/$(gcloud config get-value project)/make test```

Than git commit with --amend

**Pull request closed without merging**
