### PR TITLE
Add demonstrative end-to-end MLOps process using Vertex AI platform and Smart Analytics technology capabilities

### PR DESCRIPTION
**Pull request by luotigerlsx**
This PR add demonstrative end-to-end MLOps process using Vertex AI platform and Smart Analytics technology capabilities of GCP.

In particular two general [Vertex AI Pipeline](https://cloud.google.com/vertex-ai/docs/pipelines) 
templates has been provided:
- Training pipeline including:
  - Data processing
  - Custom model training
  - Model evaluation
  - Endpoint creation
  - Model deployment
  - Deployment testing
  - Model monitoring
- Batch-prediction pipeline including
  - Data processing
  - Batch prediction using deployed model

The repository contains the following:

```
.
├── components    : custom vertex pipeline components
├── images        : custom container images for training and serving
├── pipelines     : vertex ai pipeline definitions and runners
├── configs       : configurations for defining vertex ai pipeline
├── scripts       : scripts for runing local testing 
└── notebooks     : notebooks used development and testing of vertex ai pipeline
```

The end-to-end process of creating and running the training pipeline contains the following steps:

1. Setting up [MLOps environment](https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/tree/main/provision) on Google Cloud.
2. Create an [Artifact Registry](https://cloud.google.com/artifact-registry) for your organization to manage container images
3. Develop the training and serving logic
4. Create the components required to build and run the pipeline
5. Prepare and consolidate the configurations of the various steps of the pipeline
6. Build the pipeline
7. Run and orchestrate the pipeline

### CODE REVIEW

**Comment by luotigerlsx** [comment]
Hi @TheMichaelHu , thanks again for the review. I have addressed your comments. Please take a look.

**Comment by luotigerlsx** [comment]
@TheMichaelHu Thanks a lot for the additional comments and approval. There is still checking that couldn't be triggered, could you kindly help and maybe merge the PR if there is no further issue. Thanks.

**Comment by TheMichaelHu** [comment]
haha wow, there's a shell script linter in the cloud build pipeline.

**Comment by luotigerlsx** [comment]
> haha wow, there's a shell script linter in the cloud build pipeline.

:(. I have modified. Could you help trigger the run again. Thanks.

**Pull request merged**
