### PR TITLE
New tool: Firewall Enforcer

### PR DESCRIPTION
**Pull request by the-fool**
# New Tool - Firewall Enforcer

Automatically watches & deletes firewall rules if they fail a test.

Added folder in `/tools` with the code.

### CODE REVIEW

**Review by boredabdel — COMMENTED** [review]
Hi Thomas,

Few comments to address in this PR

In addition please run a terraform fmt before you submit your commit to format the terraform code properly

Cheers

**Comment by the-fool** [comment]
Updated to address comments - thanks!

**Pull request merged**
