### PR TITLE
nrt feature engineering in dataflow

### PR DESCRIPTION
**Pull request by stankiewicz**
hi,

adding example and framework how to calculate features for Vertex AI feature store in dataflow.
Features are calculated in near realitme, using windowing techniques and are reset when new values are no appearing for specific key. 

There is taxi pipeline implemented with example features. 
feature calculation is compatible with Vertex AI feature store 2.0.

### CODE REVIEW

**Comment by stankiewicz** [comment]
@agold-rh i've checked cloud build on my own project and it looks like it's flaky and fails on validating existing scripts, not this change. can you help?

**Comment by agold-rh** [comment]
@stankiewicz It's a file formatting issue. Take a look at the scripts in helpers, and they will show you the syntax tests.

Testing formatting for java files in ./examples/dataflow-near-realtime-feature-engineering
Some files need to be formatted in ./examples/dataflow-near-realtime-feature-engineering - FAIL
./examples/dataflow-near-realtime-feature-engineering/src/main/java/com/google/dataflow/feature/ExpireValue.java
./examples/dataflow-near-realtime-feature-engineering/src/main/java/com/google/dataflow/feature/pipeline/TaxiNRTPipeline.java
./examples/dataflow-near-realtime-feature-engineering/src/main/java/com/google/dataflow/feature/NRTFeature.java
./examples/dataflow-near-realtime-feature-engineering/src/main/java/com/google/dataflow/feature/MergeFeaturesToCSV.java
./examples/dataflow-near-realtime-feature-engineering/src/main/java/com/google/dataflow/feature/model/ClickstreamEvent.java
./examples/dataflow-near-realtime-feature-engineering/src/test/java/com/google/dataflow/feature/FeatureCalculationTest.java
make: *** [Makefile:28: test] Error 1

**Comment by stankiewicz** [comment]
Interesting. It's passing spotless with Google formatting but thanks for the pointers.

**Review by agold-rh — APPROVED** [review]

**Pull request merged**
