### PR TITLE
api_check bug fix

### PR DESCRIPTION
**Pull request by jdyke**
There was a bug introduced during PR #626 and this addresses the bug.

### CODE REVIEW

**Comment by jdyke** [comment]
> /gcbrun

This didn't look like it worked for me when I ran it earlier, is there something I need to do?

**Comment by boredabdel** [comment]
Yeah it's failing the linter and formatter.

Can you please have a look at this page and run the linter locally https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md ?

Thanks

**Comment by jdyke** [comment]
> Yeah it's failing the linter and formatter.
> 
> 
> 
> Can you please have a look at this page and run the linter locally https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md ?
> 
> 
> 
> Thanks

You got it. I'll get that going.

**Comment by jdyke** [comment]
So I ran this and its failing for a different repo. Looks like code got submitted without running the checks? Not sure if that should hold back this PR since its someone else's tool.

```
Validating ./tools/google-cloud-support-slackbot - Checking python files
./google_cloud_support_slackbot.py:182:5: F841 local variable 'token' is assigned to but never used
./google_cloud_support_slackbot.py:255:13: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:284:13: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:560:9: F841 local variable 'escalation_mask' is assigned to but never used
./google_cloud_support_slackbot.py:564:9: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:680:18: F541 f-string is missing placeholders
./google_cloud_support_slackbot.py:710:18: F541 f-string is missing placeholders
./google_cloud_support_slackbot.py:959:13: F841 local variable 'data' is assigned to but never used
Some files need to be formatted in ./tools/google-cloud-support-slackbot - FAIL
```

**Comment by jdyke** [comment]
> So I ran this and its failing for a different repo. Looks like code got submitted without running the checks? Not sure if that should hold back this PR since its someone else's tool.
> 
> ```
> Validating ./tools/google-cloud-support-slackbot - Checking python files
> ./google_cloud_support_slackbot.py:182:5: F841 local variable 'token' is assigned to but never used
> ./google_cloud_support_slackbot.py:255:13: F841 local variable 'e' is assigned to but never used
> ./google_cloud_support_slackbot.py:284:13: F841 local variable 'e' is assigned to but never used
> ./google_cloud_support_slackbot.py:560:9: F841 local variable 'escalation_mask' is assigned to but never used
> ./google_cloud_support_slackbot.py:564:9: F841 local variable 'e' is assigned to but never used
> ./google_cloud_support_slackbot.py:680:18: F541 f-string is missing placeholders
> ./google_cloud_support_slackbot.py:710:18: F541 f-string is missing placeholders
> ./google_cloud_support_slackbot.py:959:13: F841 local variable 'data' is assigned to but never used
> Some files need to be formatted in ./tools/google-cloud-support-slackbot - FAIL
> ```

Otherwise, thats the only failure. I won't be able to get that CI check cleared. Let me know what youd like to do. Thanks!

```
Some files need to be formatted in ./tools/google-cloud-support-slackbot - FAIL

make: *** [Makefile:28: test] Error 1
```

**Comment by boredabdel** [comment]
Ok Thanks. I will force this merge. Will figure out why the CI is broken

**Pull request merged**
