### PR TITLE
Tool that converts slo definition to Terraform code

### PR DESCRIPTION
**Pull request by arjunvijaygoogle**
The tool basically converts the SLO Definition in GCP to its equivalent terraform block. Following are the exhaustive list of different SLO definition covered by this tool that can be converted

Request based SLI

1. Good Total Ratio
2. Distribution cut

Window Based SLI

1. Metrics Mean
2. Metrics Sum
3. Good Total Ratio Threshold

The tool has a very basic UI where user can provide the input of SLO definition and after clicking on convert button it will be converted to terraform block

### CODE REVIEW

**Comment by arjunvijaygoogle** [comment]
@agold-rh Can you please review this

**Review by agold-rh — DISMISSED** [review]

**Comment by agold-rh** [comment]
@arjunvijaygoogle Some files need to be reformatted. If you look in the helpers directory, you can review the formatting checks that take place.

Testing formatting for java files in ./tools/slo-definition-converter
Some files need to be formatted in ./tools/slo-definition-converter - FAIL
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/utility/ReplacementMapBuilderUtility.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/utility/JsonUtility.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/utility/TextUtility.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/SlotoolsApplication.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/config/WebConfig.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/controller/JsonConverterController.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/exception/BadJsonRequestException.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/model/TimePeriod.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/model/SloTFResponse.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/model/SloJsonConverterRequest.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/service/JsonConverterService.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/service/PlaceholderReplacementService.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/constant/ReplaceConstants.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/constant/FileConstants.java
./tools/slo-definition-converter/slo-backend/src/main/java/com/tools/slo/slotools/constant/SliConstants.java
./tools/slo-definition-converter/slo-backend/src/test/java/com/tools/slo/slotools/SlotoolsApplicationTests.java
./tools/slo-definition-converter/slo-backend/src/test/java/com/tools/slo/slotools/utility/ReplacementMapBuilderUtilityTest.java
./tools/slo-definition-converter/slo-backend/src/test/java/com/tools/slo/slotools/utility/JsonUtilityTest.java
./tools/slo-definition-converter/slo-backend/src/test/java/com/tools/slo/slotools/controller/JsonConverterControllerTest.java
./tools/slo-definition-converter/slo-backend/src/test/java/com/tools/slo/slotools/service/JsonConverterServiceTest.java
make: *** [Makefile:28: test] Error 1

**Review by agold-rh — DISMISSED** [review]

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — DISMISSED** [review]

**Review by agold-rh — DISMISSED** [review]

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — DISMISSED** [review]

**Review by agold-rh — APPROVED** [review]

**Pull request merged**
