### PR TITLE
New Tool: auto exploratory data analysis and feature recommendation 

### PR DESCRIPTION
**Pull request by luotigerlsx**
Engineering Council bug ID: b/142913160

We have recently published the “Feature Recommendation Guide for Machine Learning”, which provides a comprehensive guidance on exploratory data analysis from both intuitive (visualization) and rigorous (statistical) perspectives, together with feature selection and engineering recommendations. The links can be found in the bug tickets mentioned above.

Accompanying this guide, we have developed and released our first version of  “Auto Data Exploration and Feature Recommendation Tool” that aims at automating the recommended analysis regardless of the scale of the data (using bigquery as backend compute engine), and generating a well organized report to present the findings. Practitioners from different backgrounds and with varying ML experience could benefit from using this tool.

The automated exploratory data analysis (EDA) done by the tool includes:
- Descriptive analysis of each numerical and categorical attribute in a dataset
- Correlation analysis of two attributes (numerical versus numerical, numerical versus categorical, and categorical versus categorical) through qualitative and/or quantitative analysis. 

Based on the EDA performed, feature recommendations are made, and a summary report is generated. Some snapshots of the example report are attached at the bottom.

- Descriptive Analysis
    - Missing values
    - Quantile statistics
    - Descriptive statistics
    - Distribution histogram
    - Cardinality
    - Unique counts
- Correlation Analysis
    - Qualitative Analysis
        - Contingency table
        - Descriptive table
    - Quantitative Analysis
        - Pearson correlation
        - Information gain
        - ANOVA
        - Chi-Square

### CODE REVIEW

**Comment by luotigerlsx** [comment]
@jaketf Hi jake, I have this new tools ready to be merged in to the repository. It has been shown to the engineering council also. Please help to take a look.

Btw, I find there is a new CI process integrated, but I keep getting failures and the logs didn't tell much also. Please kindly help.

**Comment by AdrienWalkowiak** [comment]
It looks like the linting check fails:

```
Some files need to be formatted in tools/ml-auto-eda - FAIL
tools/ml-auto-eda/setup.py
tools/ml-auto-eda/ml_eda/metadata/metadata_definition.py
tools/ml-auto-eda/ml_eda/metadata/run_metadata_pb2.py
tools/ml-auto-eda/ml_eda/metadata/metadata_loader.py
tools/ml-auto-eda/ml_eda/runner.py
tools/ml-auto-eda/ml_eda/datasources/bigquery/bq_client.py
tools/ml-auto-eda/ml_eda/preprocessing/preprocessor_factory.py
tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/bigquery/bq_preprocessor.py
tools/ml-auto-eda/ml_eda/preprocessing/preprocessors/data_preprocessor.py
tools/ml-auto-eda/ml_eda/preprocessing/analysis_query/query_templates.py
tools/ml-auto-eda/ml_eda/preprocessing/analysis_query/query_builder.py
tools/ml-auto-eda/ml_eda/analysis/quantitative_analyzer.py
tools/ml-auto-eda/ml_eda/analysis/descriptive_analysis.py
tools/ml-auto-eda/ml_eda/analysis/qualitative_analysis.py
tools/ml-auto-eda/ml_eda/analysis/utils.py
tools/ml-auto-eda/ml_eda/analysis/quantitative_analysis.py
tools/ml-auto-eda/ml_eda/analysis/descriptive_analyzer.py
tools/ml-auto-eda/ml_eda/reporting/report_generator.py
tools/ml-auto-eda/ml_eda/reporting/visualization.py
tools/ml-auto-eda/ml_eda/reporting/utils.py
tools/ml-auto-eda/ml_eda/reporting/template.py
tools/ml-auto-eda/ml_eda/reporting/recommendation.py
tools/ml-auto-eda/ml_eda/orchestration/analysis_run.py
tools/ml-auto-eda/ml_eda/orchestration/analysis_tracker.py
tools/ml-auto-eda/ml_eda/constants.py
tools/ml-auto-eda/tests/quantitative_analyzer_test.py
```

We use yapf for the linting check - if you feel you can fix it you can use either yapf directly or the make fmt command to fix it.

The alternative would be to mark this tool as an exception if you feel the formatting might break things or be too cumbersome to do here.

**Comment by luotigerlsx** [comment]
> We use yapf for the linting check - if you feel you can fix it you can use either yapf directly or the make fmt command to fix it.
> 
> The alternative would be to mark this tool as an exception if you feel the formatting might break things or be too cumbersome to do here.

Hi @AdrienWalkowiak , thanks a lot for the comments. Since this has been internally reviewed with the development team and we have indeed checked it against pylint, I think it makes sense to got for the option of marking the exception of yapf. Is there any reference i can refer to do that (I am not sure how it can be done.)

**Comment by AdrienWalkowiak** [comment]
Sure, you simply need to add your folder to the exclusion list in helpers/exclusion_list.txt

**Comment by luotigerlsx** [comment]
@AdrienWalkowiak thanks a lot for the help. I have added it into the exclustion_list.txt

**Pull request merged**
