### PR TITLE
Modifying kubeflow pipeline so anybody can run it on their own projects.

### PR DESCRIPTION
**Pull request by alan-krumholz**

### CODE REVIEW

**Comment by alan-krumholz** [comment]
Noted, some context.
This notebook is not the core code for this solution.
This existing solution was recently packaged into a KubeFlow pipeline in order to be able to publish the solution in the AI Hub.
I wanted to add the notebook I used to package it (into the repo) for reference.  As noted, I didn't spend much time documenting this notebook.
I'll spend some time adding more documentation/instructions for this code and will resubmit

Thanks

**Comment by alan-krumholz** [comment]
@dan-anghel  
I have added comments throughout the notebook (including detailed docs for the code building each component)

Please let me know if this is better.

Thanks!

**Comment by alan-krumholz** [comment]
@dan-anghel 
I added two new minor changes to the pull request in the sql scripts one that was preventing to use these in a different project and the other that started failing recently because of a lack of casting.

Were you able to run the pipeline code:

here are the instructions on how to deploy kubeflow and run the notebook in their hosted notebooks:
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart/

Thanks!

**Comment by dan-anghel** [comment]
@alan-krumholz 

Sorry for the delay in the review. I finally managed to run the notebook. It would be probably worth adding in the notebook the fact that it needs to be run on Kubeflow and the link to the installation instructions. Thank you for making the suggested modifications.

LGTM

**Comment by alan-krumholz** [comment]
@dan-anghel 
Thanks so much!
I added instruction on how to deploy the cluster to the notebook.

I don't seem able to merge this pull request. it seems only authorized user can do that (and I don't seem to be one of them :))

Can you please help me merge this?


Thanks!

**Comment by dan-anghel** [comment]
@alan-krumholz I'm not authorized either to do the merge:)

@jaketf Would you mind merging this pull request? Thank you!

**Pull request merged**
