### PR TITLE
New Dashboard Template and Permission checks

### LINKED ISSUE #938: examples/billboard/billboard.py - Permission Denied
Hi, 
Created export standard and detailed billing information to bq.  Run the code from cloudshell. I have I followed the tutorial from bit.ly/billboard-template and I see an error:
`Permission Denied so you do not have project level permission or provided wrong project id, please check.`

I have roles assigned:
- Billing Administrator
- Owner
- Security Admin
- BigQuery Admin
- Organization Administrator

I tested it in two different gcp organizations and the result is the same. project_id get from PROJECT_ID env and this is the project where I run the python and where is bq with data.

set of my libs:
`cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.6
google-api-core==2.10.2
google-auth==2.14.1
google-cloud-bigquery==3.4.0
google-cloud-bigquery-storage==2.16.2
google-cloud-billing==1.7.3
google-cloud-core==2.3.2
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
grpc-google-iam-v1==0.12.4
grpcio==1.50.0
grpcio-status==1.50.0
idna==3.4
numpy==1.23.5
packaging==21.3
proto-plus==1.22.1
protobuf==4.21.9
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
requests==2.28.1
rsa==4.9
six==1.16.0
urllib3==1.26.13`

### PR DESCRIPTION
**Pull request by ayapsone**
- New Dashboard Template 
- Check billing api enabled or not
- closes #938

### CODE REVIEW

**Review by NimishC — APPROVED** [review]

**Review by aymanfarhat — APPROVED** [review]
LGTM

**Comment by ayapsone** [comment]
@aymanfarhat - I'm not sure how it can fail for formatting error as I was able merge after testing python2/python3 yapf formatting locally + our normal CI does testing while doing pull request before LGTMs.

**Comment by jnewland** [comment]
I experienced the following error in Looker Studio when attempting to use `billboard.py` from this PR:

> Something went wrong when building your report
> ds93 is not a valid data source alias for this report.

Removing the portion of the url referencing `ds93` results in the successful creation of a report, but I'm not sure if functionality is degraded without access to the detailed billing datasource.

**Comment by ayapsone** [comment]
@jnewland - I'm trying to fix removing that but since this build failed, I'm just waiting for it. probably will do a fresh pull request.

**Comment by ayapsone** [comment]
> I experienced the following error in Looker Studio when attempting to use `billboard.py` from this PR:
> 
> > Something went wrong when building your report
> > ds93 is not a valid data source alias for this report.
> 
> Removing the portion of the url referencing `ds93` results in the successful creation of a report, but I'm not sure if functionality is degraded without access to the detailed billing datasource.

i fixed that so you should be good after the merge

**Pull request merged**
