### PR TITLE
Prune columns over 10,000.

### PR DESCRIPTION
**Pull request by bmenasha**
Corrects issue 533 by removing any properties over the 10,000 limit.
Also speed up remove_duplicates by processing each dict once.

### CODE REVIEW

**Comment by ocervell** [comment]
@AdrienWalkowiak @morgante could one of you please merge this asap ? Thank you 👍

**Comment by morgante** [comment]
302 -> @jaketf

**Comment by jaketf** [comment]
@morgante what does 301 mean?

**Comment by morgante** [comment]
@jaketf Just a tongue-in-cheek "301 redirect" since I'm not in PSO/maintaining this repo any more.

**Pull request merged**
