### PR TITLE
Update FeatureOnlineStore Migration Kit 

### PR DESCRIPTION
**Pull request by kkram01**
This PR aims to add enhancements to the FeatureStore migration based on the feedback received.

1. add a flag "--create-resources" to separate BQExport of Legacy featurestore and creation of FeatureOnlineStore resources as a part of the migration process

2. Add terraform reference examples as a quick start guide on creation of FeatureOnlineStore resources using terraform.

3. Documentation updates w.r.to the above changes

### CODE REVIEW

**Comment by kkram01** [comment]
Hi @agold-rh , could you please take a look?

**Comment by agold-rh** [comment]
Screenshot 2024-11-13 at 9 54 33 AM
@kkram01 Your build failed. Please see the attached screenshot.

**Comment by kkram01** [comment]
Hi @agold-rh It looks like this is an issue w.r.to pulling the image mentioned in the Makefile in the root directory of the repo. I haven't made any changes to that. any idea why this is happening?

**Review by agold-rh — APPROVED** [review]

**Pull request merged**
