### PR TITLE
New add_load_date_suffix import option.

### PR DESCRIPTION
**Pull request by bmenasha**
With the new import option , the pipeline will now create
a new BigQuery table for each new load date. This helps handle API incompatible
schema changes better as each day's imports only need to be consistent rather
then all prior imports.

### CODE REVIEW

**Comment by bmenasha** [comment]
those failures aren't related to this commit but caused by the a merge. i would fix them myself but would rather @TheLanceLord  take a look and resolve them in a different PR as perhaps it will help find bugs in that tool.  I manually resolved them locally and the cloud-build pipeline was clean afterwards.

Thanks @TheLanceLord  for writing that  bot, i've had customers asking for that very thing in the past and am very happy you took the effort to write it.

**Comment by TheLanceLord** [comment]
Yep, I'll take a look into it and see what I broke

**Comment by boredabdel** [comment]
@TheLanceLord This is the PR that broke our CI https://github.com/GoogleCloudPlatform/professional-services/pull/673

Can you have a look please ?

**Comment by boredabdel** [comment]
@TheLanceLord I run the linter locally, here are the errors i get

```Validating ./tools/google-cloud-support-slackbot - Checking python files
./google_cloud_support_slackbot.py:182:5: F841 local variable 'token' is assigned to but never used
./google_cloud_support_slackbot.py:255:13: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:284:13: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:560:9: F841 local variable 'escalation_mask' is assigned to but never used
./google_cloud_support_slackbot.py:564:9: F841 local variable 'e' is assigned to but never used
./google_cloud_support_slackbot.py:959:13: F841 local variable 'data' is assigned to but never used
Some files need to be formatted in ./tools/google-cloud-support-slackbot - FAIL

make: *** [Makefile:28: test] Error 1
```

I will add the tools/google-cloud-support-slackbot to the exclusion list for now so it doesn't break CI for everything else. I will open an issue and assign it to you

**Pull request merged**
