### PR TITLE
Vertex AI Endpoint Stress Tester

### PR DESCRIPTION
**Pull request by suddhasatwabhaumik**
Hello,

This is an automated utility to stress-test a Vertex AI endpoint on a model available in Vertex AI Model Registry.
This utility, as used in multiple PSO engagements have proved very essential in choosing the right size of a Vertex AI Endpoint for a given ML model.

Please review the work, and let me know for improvements.

Thank you!

### CODE REVIEW

**Review by agold-rh — APPROVED** [review]

**Comment by agold-rh** [comment]
@suddhasatwabhaumik The build trigger failed with a syntax error. Please see the attached image.
Screenshot 2024-08-16 at 10 40 42

**Comment by suddhasatwabhaumik** [comment]
> @suddhasatwabhaumik The build trigger failed with a syntax error. Please see the attached image. Screenshot 2024-08-16 at 10 40 42

@agold-rh : This is updated now. Please advise.

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — APPROVED** [review]

**Review by agold-rh — APPROVED** [review]

**Pull request merged**
